spring.application.name=SmartStay

spring.datasource.url=jdbc:mysql://localhost:3306/pg_accommodation_db
spring.datasource.username=root
spring.datasource.password=Tanishq@2002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
gemini.model=gemini-flash-latest
gemini.api.key=AQ.Ab8RN6Ihkeidt5RZm7byCvvIYFKx9gNADGGNU__XDKclCycfrg
